name: Docker Image CI

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production 

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          itnotf/edgeone-dynamic-origin:${{ github.ref_name }}
          itnotf/edgeone-dynamic-origin:latest